# Generated by Django 4.2 on 2023-04-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_rating', '0004_book_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_by',
        ),
    ]
